server:
  port: 8080

spring:
  application:
    name: order-service

  datasource:
    url: ${ORDERS_DB_URL:jdbc:postgresql://localhost:5433/orders}
    username: ${ORDERS_DB_USER:orders}
    password: ${ORDERS_DB_PASSWORD:orders}

  sql:
    init:
      mode: always

  # The shipping-service HTTP client
  http:
    serviceclient:
      shipping:
        base-url: ${SHIPPING_BASE_URL:http://localhost:8081}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [order-service,%X{correlationId:-}] %logger{24} : %msg%n"
