server:
  port: 8081

spring:
  application:
    name: shipping-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: shipping-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [shipping-service,%X{correlationId:-}] %logger{24} : %msg%n"
