-- The system of record: a perfectly ordinary normalized write model.
-- Note what is NOT here: nothing shaped like the member-activity dashboard.

CREATE TABLE members (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      TEXT NOT NULL,
    email     TEXT NOT NULL UNIQUE,
    joined_on DATE NOT NULL
);

CREATE TABLE books (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn   TEXT NOT NULL UNIQUE,
    title  TEXT NOT NULL,
    author TEXT NOT NULL,
    copies INT  NOT NULL CHECK (copies > 0)
);

CREATE TABLE loans (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   BIGINT NOT NULL REFERENCES members (id),
    book_id     BIGINT NOT NULL REFERENCES books (id),
    borrowed_on DATE   NOT NULL,
    due_on      DATE   NOT NULL,
    returned_on DATE
);

CREATE INDEX idx_loans_member ON loans (member_id);
CREATE INDEX idx_loans_book ON loans (book_id);
